language: node_js
node_js:
    - '10.11.0'

cache: npm

branches:
    only:
        - master

before_script:
    - npm i -g npm@latest

install:
    - npm ci
    - npm --prefix functions ci

script:
    - npm run build -- --configuration=production
    - npm --prefix functions run build

after_success:
    - npx firebase deploy --token $FIREBASE_TOKEN

notifications:
    email:
        on_failure: change
        on_success: change
