import { NgModule } from '@angular/core';

import {
	MatSidenavModule,
	MatToolbarModule,
	MatIconModule,
	MatButtonModule,
	MatListModule,
	MatCardModule,
	MatInputModule,
	MatFormFieldModule,
	MatDatepickerModule,
	MatNativeDateModule,
	MatSelectModule,
	MatDividerModule,
	MatDialogModule,
	MatTableModule,
	MatProgressBarModule,
	MatSortModule,
	MatChipsModule,
	MatSnackBarModule,
	MatTabsModule,
	MatTooltipModule,
	MatProgressSpinnerModule,
	MatCheckboxModule,
	MatMenuModule
} from '@angular/material';

@NgModule({
	imports: [
		MatSidenavModule,
		MatToolbarModule,
		MatIconModule,
		MatButtonModule,
		MatListModule,
		MatCardModule,
		MatInputModule,
		MatFormFieldModule,
		MatDatepickerModule,
		MatNativeDateModule,
		MatSelectModule,
		MatDividerModule,
		MatDialogModule,
		MatTableModule,
		MatProgressBarModule,
		MatSortModule,
		MatChipsModule,
		MatSnackBarModule,
		MatTabsModule,
		MatTooltipModule,
		MatProgressSpinnerModule,
		MatCheckboxModule,
		MatMenuModule
	],
	exports: [
		MatSidenavModule,
		MatToolbarModule,
		MatIconModule,
		MatButtonModule,
		MatListModule,
		MatCardModule,
		MatInputModule,
		MatFormFieldModule,
		MatDatepickerModule,
		MatNativeDateModule,
		MatSelectModule,
		MatDividerModule,
		MatDialogModule,
		MatTableModule,
		MatProgressBarModule,
		MatSortModule,
		MatChipsModule,
		MatSnackBarModule,
		MatTabsModule,
		MatTooltipModule,
		MatProgressSpinnerModule,
		MatCheckboxModule,
		MatMenuModule
	]
})
export class MaterialModule {}
